Support multiple COS instances scenario
open-toolchain/simple-vsi-toolchain pull request #15
Opened 2021-03-29 07:24 UTC by akshaykumar-vijapur

The following are the scenarios.

1. If user does not have any COS instance, Then toolchain will create a COS instance in `Lite Plan` with name as toolchain name and use it for further bucket creation.
2. if user has only one Instance, Then we assume that user is on `Lite Plan`. We will not create a new instance but re-use the same instance for the bucket creation.
3.  if user has more then Instance, Then we will create a COS instance with the name of the instance will be toolchain name and use it for further bucket creation.

### Description

---

### Testing Done

---

### Related Issues

2021-03-29 09:42 UTC, mundrapiyush36 requested changes

2021-03-29 09:42 UTC, mundrapiyush36 commented on .build_pipeline/task.yaml
> +              }
@akshaykumar-vijapur Just got confused with the || condition here. What's going on in this code block ?

2021-03-29 09:42 UTC, mundrapiyush36 commented on .build_pipeline/task.yaml
> +            fi
Proceeding with the creation of Cloud Object Storage Instance with name ${INSTANCENAME} under Standard Plan.

2021-03-29 09:47 UTC, akshaykumar-vijapur commented on .build_pipeline/task.yaml
> +              }
@mundrapiyush36  It acts like a `try catch` block. Seems like we cannot find if a user is on lite/standard plan with `CLI`. So we will try to create a instance with `lite` plan,  if it works fine, else we will proceed with creation of instance with `standard` account.

2021-03-30 14:08 UTC, mundrapiyush36 approved these changes

2021-03-30 14:08 UTC, mundrapiyush36 commented on .build_pipeline/task.yaml
> +              ibmcloud resource service-instance-create "$INSTANCENAME" cloud-object-storage lite global && echo "Instance creation successfull.."
Instance creation successful.

2021-03-30 14:08 UTC, mundrapiyush36 commented on .build_pipeline/task.yaml
> +              ibmcloud resource service-instance-create "$INSTANCENAME" cloud-object-storage standard global && echo "Instance creation successfull.."
Instance creation successful.

2021-03-30 14:37 UTC, merged