Update the UI with COS instance details
open-toolchain/simple-vsi-toolchain pull request #17
Opened 2021-03-29 09:24 UTC by akshaykumar-vijapur

2021-03-29 09:43 UTC, mundrapiyush36 requested changes

2021-03-29 09:43 UTC, mundrapiyush36 commented on .bluemix/cos.json
> +        "title": "Cloud Object Storage is used to store the artifacts generated by the Pipeline. If you have a COS Instance and Bucket in your resources, then provide Bucket name and service API-Key
@akshaykumar-vijapur Just provide snapshot of the UI. We may need to reformat the information to cater to the UX.

2021-03-29 10:17 UTC, akshaykumar-vijapur commented
![Uploading image.png…]()

2021-03-30 05:45 UTC, pradeep-b commented
Make it a single sentence in the UI instead of a bullet list. Retain the 3-bullet format in the ReadMe.

In the UI
If you have multiple COS instances, please specify the name of the bucket you would like to be used. Otherwise a new instance with a new bucket will be created with the name specified below.

In the ReadMe
  - If the user does not have any COS instance, a COS instance with same name as toolchain name will be created and it would be used to create the bucket.
  - If the user has only one COS Instance, the same instance will be used for the creating the bucket.
  - If the user has two or more COS Instances, a COS instance with the same name as that of the toolchain will be created and it will be used for creating the bucket.

2021-03-30 07:47 UTC, akshaykumar-vijapur commented
Updated Ui 
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/80688656/112952566-41165980-915a-11eb-830a-98446911b1af.png">

2021-03-30 07:52 UTC, mundrapiyush36 approved these changes

2021-03-30 07:52 UTC, mundrapiyush36 commented on .bluemix/cos.json
> +        "title": "Cloud Object Storage is used to store the artifacts generated by the Pipeline. If you have a COS Instance and Bucket in your resources, then provide Bucket name and service API-Key
Cloud Object Storage is used to store the artifacts generated by the pipeline. If you have a COS Instance and bucket, then provide bucket name and service API Key to access the bucket in the below form, else skip this section. &nbsp;   COS Instance creation/reuse depends on the following scenarios. \\n 1. If user does not have a COS Instance, toolchain will create a default instance and bucket for the user with the name as that of toolchain. \\n If user have one COS Instance then toolchain will reuse the instance and create a bucket under same instance. \\n If user have more then one COS Instance then toolchain will create a COS instance with the name as that of toolchain.  For help, please visits the [Cloud Object Storage documentation](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-getting-started-cloud-object-storage).

2021-03-30 08:58 UTC, padraic-edwards commented on .bluemix/cos.json
> +        "title": "Cloud Object Storage is used to store the artifacts generated by the Pipeline. If you have a COS Instance and Bucket in your resources, then provide Bucket name and service API-Key
Cloud Object Storage is used to store the artifacts generated by the pipeline. If you have a COS instance and bucket, please provide the bucket name and service API Key to access the bucket in the below form, else skip this section.   COS Instance creation/reuse depends on the following scenarios. \n\n 1. If you do not have a COS Instance the toolchain will create a default instance and bucket for you using the name of the toolchain. \n\n 2. If you have one COS instance the toolchain will reuse this instance and create a bucket under same instance. \n\n 3. If you have more than one COS Instance then the toolchain will create a COS instance using the toolchain name. For additional information, please visit the [Cloud Object Storage documentation](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-getting-started-cloud-object-storage).

2021-03-30 09:16 UTC, padraic-edwards commented on .bluemix/cos.json
> +        "title": "Cloud Object Storage is used to store the artifacts generated by the Pipeline. \n\nIf you have multiple COS instances, please specify the name of the bucket you would like to be use
Cloud Object Storage is used to store the artifacts generated by the pipeline. \n\nIf you have multiple COS instances, please specify the name of the bucket you would like to use. Otherwise a new instance with a new bucket will be created with the name specified below.

2021-03-30 10:44 UTC, closed without merging